print("*****Execises 1*****")
name=input("Enter Your Name :")
print("Hello ",name)
print("***Exercise 2*******")
h=int(input("Enter Hours "))
r=float(input("Enter Rate "))
#print("Hours :",h)
#print("Rate :",r)
print("Pay :",float(h*r))
print("*****Excercise 3*******")
w=int(input("Width ="))
hi=float(input("Height ="))
print(w//2)
print(w/2.0)
print(hi/3)
print(1+2*5)
print("*********Exercise 4********")
print("Converting Celsius Temparature to Fahrenheit Temparature")
ct=int(input("Enter the Celsius Temparature = "))
ft=ct*1.8+32
print("Coverted Temparature =",ft)
